[build]
  command = "sed -i 's|%SUPABASE_URL%|'\"$SUPABASE_URL\"'|g; s|%SUPABASE_ANON_KEY%|'\"$SUPABASE_ANON_KEY\"'|g' index.html"
  publish = "."

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
